# env
env: development
url: "http://example.com"
host: "127.0.0.1"
port: 8857
oauth_domains:
  - "example.com"
  - "localhost"
# redis url
redis_url: redis://127.0.0.1:6379
# wechat mp accounts
accounts:
  - name: my-awesome-mp         # name of account
    app_id: wx1234567890        # appId of account
    app_secret: abcdefghijklmn  # appSecret of account
    orignal_id: gh_xxxxxxx      # orignalId of account
# rules
rules:
  - match:
      ToUserId:
    text: "hello world"
    http_sync: "http://example.com/handle"
    http_async: "http://example.com/handle"
